### PR TITLE
added tile for 57 and renamed other tiles

### LINKED ISSUE #1: Add all LCZ types
Currently we only have tiles for the LCZ types needed for our Amsterdam map. Would be nice to complete the set so it would work globally.

### PR DESCRIPTION
**Pull request by Morrizzzzz**
@Peter9192 Could you double check? 

closes #1

### CODE REVIEW

**Comment by Morrizzzzz** [comment]
@Peter9192 please double check

**Review by Peter9192 — CHANGES_REQUESTED** [review]
I tried to run this, but tile3 seems to be a bit different from the others. The others look like this:

```
In [4]: gpd.read_file(f"{tiles}/tile_4_wgs84_58.gpkg").geometry.item()
Out[4]: <MULTIPOLYGON (((4.884 52.398, 4.884 52.398, 4.884 52.397, 4.884 52.397, 4.8...>
```

tile 3 looks like this:

```
In [3]: gpd.read_file(f"{tiles}/tile_3_wgs84_57.gpkg").geometry
Out[3]:
0     POLYGON ((4.88378 52.39765, 4.88387 52.39765, ...
1     POLYGON ((4.88423 52.39810, 4.88432 52.39810, ...
2     POLYGON ((4.88423 52.39792, 4.88432 52.39792, ...
...
```

so instead of a single multipolygon, it has multiple single polygons. Subtle difference, but it breaks the code.

**Comment by Morrizzzzz** [comment]
I updated the tile should work now @Peter9192

**Review by Peter9192 — APPROVED** [review]
Now it works 👍

**Comment by Peter9192** [comment]
Thanks for adding it :-)

**Pull request merged**
